#!/usr/bin/env bash

set -eu -o pipefail

testdir=$(cd "$(dirname "$0")"/../test; pwd)

docker build --tag iheanyi1989/vpc-pipeline-image:v1.0.1 workflows/resource/configure/vpcpipeline/vpc-vpc-pipeline-image

docker push iheanyi1989/vpc-pipeline-image:v1.0.1